### ISSUE TITLE
[Question] Providing an example of usage.

### ISSUE THREAD

**Issue by Joey-Robinson** [vilst3r/dota2-web-api#5]
I was playing around with this but was getting dota2webapi is not a constructor. I was wondering if you could provide a usage for this so I can see how it's being used. I'm copy/pasting your require statement & api variables like shown in your readme, just wanted to double check.

**Comment by vilst3r** [comment]
@Joey-Robinson Hi Joey, 

It's been a while but this is how I currently use my SDK in one of my sample web apps (https://github.com/vilst3r/dotastuff/blob/master/server.js)
```
/**
 * Express configuration
 */
const server = express()
server.set('host', app.host)
server.set('port', app.port)
server.set('env', app.env)
server.locals.api = new dotaWebAPI(api.key) 
```

You just need to pass in your Steam API key (from Steam) and it should be able to pull data from the Steam DB.

Let me know if there's any more problems and post a screenshot if the problem persists. In the meantime, I'll find time to update the README.md when I'm free :)

Cheers!
